# Generated by Django 3.2 on 2021-07-10 07:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_public',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 7, 36, 38, 478360, tzinfo=utc)),
        ),
    ]
