# Generated by Django 3.2 on 2021-07-10 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210710_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 7, 39, 1, 378891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
